[build]
rustflags = [
    "-C", "force-frame-pointers=yes",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "force-frame-pointers=yes",
    "-C", "link-arg=-z",
    "-C", "link-arg=common-page-size=2097152",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=2097152",
]
